[FILESV]
;工程、ユーザ単位の農水省標準ダイアログ作業フォルダ
FILEIO=D:\HP\BRA\(kotei)\(kyoten)\DATA\FILEIO\(user)

;作業フォルダ
WORK=D:\HP\BRA\(kotei)\(kyoten)\DATA\WORK\(user)

[CSV]
;調査票OCRデータ格納フォルダ
OCRINPATH=H:\MAFF\OCRSAVEFILE\BRA1S

;調査票オンラインデータ格納フォルダ
ONLINEINPATH=H:\MAFF\OCRSAVEFILE\BRA1S

[EXCEL]
;EXCEL帳票用データ格納フォルダ
INPATH=I:\HP\BRA\(kotei)\(kyoten)\DATA\LIST_DATA\EXCEL_INPUT

;EXCEL帳票格納フォルダ
OUTPATH=I:\HP\BRA\(kotei)\(kyoten)\DATA\LIST_DATA\EXCEL_OUTPUT

;EXCEL入力画面フォルダ
SCREEN=D:\HP\BRA\(kotei)\EXCEL

;EXCEL帳票雛形フォルダ
REPORT=D:\HP\BRA\(kotei)\EXCEL

[DB]
;BCP(Bulk Copy Program)ユーティリティの実行ファイルパス
BCPEXEPATH=C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\bcp.exe

[LOG]
;ユーザログファイルパス
USERLOGPATH=I:\HP\Log\(date)(time)_(user)_BRA_農業経営統計.csv

;システムログファイルパス
SYSTEMLOGPATH=I:\HP\Log_トレース\BRA\(kotei)\(kyoten)\(user)\(date)(time)_(user)_BRA_農業経営統計.csv

;ユーザログ出力レベル(Debug:0 Info:1 Warn:2 Err:3 Fatal:4)
USERLOGLEVEL=0

;システムログ出力レベル(Debug:0 Info:1 Warn:2 Err:3 Fatal:4)
SYSTEMLOGLEVEL=3

;出力制限サイズ(Byte)
MAXSIZE=1024000

;履歴件数
HISTORYCOUNT=5

[SENMONCHOSAIN]
;専門調査員EXCEL帳票用データ格納フォルダ
INPATH=T:\(user)\EXCEL_INPUT

;専門調査員EXCEL帳票格納フォルダ
OUTPATH=T:\(user)\EXCEL_OUTPUT

[BACKUP]
;バックアップフォルダ
PATH=I:\HP\BRA\(kotei)\(kyoten)\DATA\BKUP

[LOCK]
;存在確認
LOCKPARENTPATH=I:\HP\BRA\(kotei)
;ロックファイルフォルダ
LOCKFILEPATH=I:\HP\BRA\(kotei)\(kyoten)\HAITA\LIST